### ISSUE TITLE
Testing out multi-item tracker

### ISSUE THREAD

**Issue by JeremiahClapfoot** [JeremiahClapfoot/testingtransfering#1]
### Devbranch 4.20

- [ ] Fix the shit
- [ ] Do this too
- [ ] If we have time
- [ ] Nice to have
